# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeApp
  
  pod 'SwiftLint'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Database'
  pod 'Firebase/Crashlytics'
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage', '~> 4.1'

  target 'PokeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokeAppUITests' do
    # Pods for testing
  end

end
